systemLog:
    destination: file
    path: "./mongod.log"
    logAppend: true
storage:
    dbPath: "./data/db"
    directoryPerDB: true
    journal:
        enabled: true
processManagement:
    fork: false
net:
    bindIp: 127.0.0.1
    port: 27017
    wireObjectCheck : false
    unixDomainSocket: 
        enabled : true
setParameter:
    enableLocalhostAuthBypass: false

